# Generated by Django 5.0.6 on 2024-06-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsfApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
