# Generated by Django 5.0.6 on 2024-07-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsfApp', '0005_remove_post_post_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_text',
            field=models.TextField(default='Default project text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(default='Default project text'),
        ),
    ]
