# Generated by Django 5.0.6 on 2024-07-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsfApp', '0006_project_project_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_name',
            field=models.CharField(default='Default project text', max_length=100),
        ),
    ]
