# Generated by Django 5.0.6 on 2024-07-04 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsfApp', '0009_user_alter_member_options_alter_member_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='envent_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
