# Generated by Django 5.0.6 on 2024-06-10 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=100)),
                ('comment_text', models.TextField()),
                ('comment_created_at', models.DateTimeField(auto_now_add=True)),
                ('comment_deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('donation_value', models.IntegerField(default=0)),
                ('member_matricula', models.BigIntegerField(default=0)),
                ('comments_allowed', models.BooleanField(default=False)),
                ('donation_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('donation_allowed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tsfApp.user')),
                ('member_id', models.CharField(max_length=100)),
                ('events_allowed', models.BooleanField(default=True)),
                ('settings_allowed', models.BooleanField(default=False)),
            ],
            bases=('tsfApp.user',),
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('event_location', models.CharField(max_length=100)),
                ('event_image', models.ImageField(upload_to='event_images')),
                ('event_created_at', models.DateTimeField(auto_now_add=True)),
                ('event_deleted_at', models.DateTimeField(auto_now_add=True)),
                ('event_hours_value', models.IntegerField(default=0)),
                ('event_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsfApp.comment')),
                ('envent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsfApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.CharField(max_length=100)),
                ('donation_value', models.IntegerField()),
                ('donation_created_at', models.DateTimeField(auto_now_add=True)),
                ('donation_deleted_at', models.DateTimeField(auto_now_add=True)),
                ('donation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsfApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsfApp.user'),
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100)),
                ('post_text', models.TextField()),
                ('post_image', models.ImageField(upload_to='post_images')),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
                ('post_deleted_at', models.DateTimeField(auto_now_add=True)),
                ('post_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsfApp.comment')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsfApp.user')),
            ],
        ),
    ]
