# Generated by Django 5.0.6 on 2024-07-03 18:22

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsfApp', '0008_remove_event_envent_user_remove_member_user_ptr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('donation_value', models.IntegerField(default=0)),
                ('member_matricula', models.BigIntegerField(default=0)),
                ('comments_allowed', models.BooleanField(default=False)),
                ('donation_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='envent_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tsfApp.user'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsfApp.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsfApp.user'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
