# Generated by Django 5.0.6 on 2024-07-04 16:00

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tsfApp', '0010_alter_event_envent_user_alter_donation_donation_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('additional_field', models.CharField(max_length=100)),
                ('events_allowed', models.BooleanField(default=True)),
                ('settings_allowed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='0', max_length=100)),
                ('name', models.CharField(default='0', max_length=100)),
                ('email', models.EmailField(default='0', max_length=100)),
                ('password', models.CharField(default='0', max_length=100)),
                ('phone', models.CharField(default='0', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('donation_value', models.IntegerField(default=0)),
                ('comments_allowed', models.BooleanField(default=False)),
                ('donation_allowed', models.BooleanField(default=False)),
            ],
        ),
    ]
